name: flow_compose
description: "flow chart for flutter."
version: 0.0.5
homepage: https://github.com/guchengxi1994/flow_compose

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

