name: flow_compose
description: "flow chart for flutter (FOR FUN)."
version: 0.0.1+7
homepage: https://github.com/guchengxi1994/flow_compose

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

